## Multiple Linear Regression

* The aim of Multi-Linear Regression algotithm is to find the linear function expressing the relationship between dependent variable and independent variables.


* There are more than one independent variable

In [1]:
import pandas as pd
ad = pd.read_csv("Advertising.csv", usecols = [1,2,3,4])
df = ad.copy()
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [5]:
X = df.drop("sales", axis = 1)
X[0:10]
# X is independent variables

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4
5    8.7   48.9       75.0
6   57.5   32.8       23.5
7  120.2   19.6       11.6
8    8.6    2.1        1.0
9  199.8    2.6       21.2

In [7]:
y = df["sales"]
y[0:10]
# y is dependent variable

0    22.1
1    10.4
2     9.3
3    18.5
4    12.9
5     7.2
6    11.8
7    13.2
8     4.8
9    10.6
Name: sales, dtype: float64

In [8]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train ,y_test = train_test_split(X, 
                                                    y,
                                                    test_size=0.20, 
                                                    random_state=42)

In [11]:
X_train.shape

(160, 3)

In [12]:
y_train.shape

(160,)

In [13]:
X_test.shape

(40, 3)

In [14]:
y_test.shape

(40,)

In [15]:
training=df.copy()

In [17]:
training.shape

(200, 4)

## 1-)Modelling with STATSMODELS.API library

In [18]:
import statsmodels.api as sm

In [19]:
lm=sm.OLS(y_train,X_train)

In [20]:
model=lm.fit()

In [21]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                  sales   R-squared (uncentered):                   0.982
Model:                            OLS   Adj. R-squared (uncentered):              0.982
Method:                 Least Squares   F-statistic:                              2935.
Date:                Thu, 04 Feb 2021   Prob (F-statistic):                   1.28e-137
Time:                        23:08:22   Log-Likelihood:                         -336.65
No. Observations:                 160   AIC:                                      679.3
Df Residuals:                     157   BIC:                                      688.5
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
TV             0.0531      0.001     36.467      0.000       0.050       0.056
radio          0.2188      0.011     20.138      0.000       0.197       0.240
newspaper      0.0239      0.008      3.011      0.003       0.008       0.040
==============================================================================
Omnibus:                       11.405   Durbin-Watson:                   1.895
Prob(Omnibus):                  0.003   Jarque-Bera (JB):               15.574
Skew:                          -0.432   Prob(JB):                     0.000415
Kurtosis:                       4.261   Cond. No.                         13.5
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [22]:
model.summary().tables[1]

<class 'statsmodels.iolib.table.SimpleTable'>

## 2-) Modelling with Scikit-Learn library

In [23]:
from sklearn.linear_model import LinearRegression

In [25]:
lm1=LinearRegression()
model1=lm1.fit(X_train,y_train)

In [28]:
model1.intercept_ # the constant number of the model equation

2.979067338122629

In [30]:
model1.coef_ # the coefficients of the indepentdent variables

array([0.04472952, 0.18919505, 0.00276111])

## 3-) Predicting  by multi linear regression model

**The Equation of the model:** 
  
   * Sales = 2.97 + TVx0.04 + radio x 0.18 + newspaperx 0.002

In [36]:
new_data=[[30], [10],[40]]
new_data = pd.DataFrame(new_data).T
new_data


# [30] correspond to  new spending of the TV advertisement

# [10] correspond to  new spending of the Radio advertisement

# [40] correspond to  new spending of the Newspaper advertisement

0   1   2
0  30  10  40

In [37]:
model1.predict(new_data)

array([6.32334798])

In [38]:
import numpy as np
from sklearn.metrics import mean_squared_error, r2_score

In [39]:
rmse_training = np.sqrt(mean_squared_error(y_train, model1.predict(X_train)))

rmse_training

# we applied the mean_squared_error method our training data set 
# thus the value of mean_squared_error (train error)  belongs to training data 

1.644727765644337

In [40]:
rmse_test = np.sqrt(mean_squared_error(y_test, model1.predict(X_test)))

rmse_test

# we applied the mean_squared_error method our test data set 
# thus the value of mean_squared_error(test error)  belongs to testdata set 

1.7815996615334502

## 4-) Model Tuning

In [41]:
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [44]:
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size=0.20, 
                                                    random_state=144)
lm2 = LinearRegression() 
model2 = lm2.fit(X_train, y_train)

* In the above code, if we change the number of **random_state** (for example, writing numbers like 90, 85, 42 instead of 144),**the values of train and test error** wil be change.



* **Random_state** determines and selects the indexes of observation values that wil be placed in the training and test sets. In other words, it determines which of the observation values in the data set will be included in the training group and which one will be in the test group.


* If we use different random state numbers, the model will be created  by using  observation values which have  different indexes, so training and test errors will have different values each time.


* Well, whichever random state value we choose, we will choose the most correct one. For this, we apply **k-fold cross valdation** for  training and test set and find the most accurate value.


* With k-fold cross validation, we divide the training and test set by the k value which we chose and reach different error values each time. And by taking the average of these different error, we reach a more optimum error.


* For example we assigned k=10. we find training errors with 10 different values by using k-fold cross validtion.By taking the mean of these 10 different values, the most appropriate error value for the training set is found.

In [45]:
np.sqrt(mean_squared_error(y_train, model2.predict(X_train)))

1.6748559274650712

In [47]:
np.sqrt(mean_squared_error(y_test, model2.predict(X_test)))

1.6640263686701036

In [48]:
model.score(X_train, y_train) # this indicate r-square value

0.8971614078663419

In [50]:
from sklearn.model_selection import  cross_val_score, cross_val_predict

In [51]:
cross_val_score(model2, 
                X_train,
                y_train, 
                cv = 10, 
                scoring = "r2")

# these all values are R-squared

array([0.86580772, 0.92273806, 0.90690214, 0.9124702 , 0.69765146,
       0.92654282, 0.92526348, 0.94823778, 0.92941476, 0.69875488])

In [52]:
cross_val_score(model2, 
                X_train, 
                y_train, 
                cv = 10, 
                scoring = "r2").mean()

# this value(0.8733783298422942) is more accurate R-squared value
# the previous value of R-squared is 0.8971614078663419 

0.8733783298422942

In [53]:
np.sqrt(-cross_val_score(model2, 
                X_train, 
                y_train, 
                cv = 10, 
                scoring = "neg_mean_squared_error")).mean()

# this value(1.6649345607872927) is  root mean_squared_error of traning data set after applying  k-fold cross validation. 


# previous value  is 1.6748559274650712

1.6649345607872927

In [54]:
np.sqrt(-cross_val_score(model2, 
                X_test, 
                y_test, 
                cv = 10, 
                scoring = "neg_mean_squared_error")).mean()

#this value(1.7399924960346644) is  root mean_squared_error of test data set after applying  k-fold cross valdation.


#  previous value  is 1.6640263686701036

1.7399924960346644